### PR TITLE
Adding rough translation of Survival Hunter

### PR DESCRIPTION
**Pull request by ivanvza**
Converted majority of the code to the latest code revamp.

The rotation is definitely not optimal but it is in a working state.

### CODE REVIEW

**Comment by ivanvza** [comment]
The Rotation implemented seems very smooth and in a working state, I have not yet implemented for all the traits/legendaries as I am still trying to figure out the correct way of using the wildfire bombs.
The traits used for this are: 3111212 and 3111222

**Comment by Kutikuti** [comment]
Thank you for the proposal. Why the change to the BM file tho ?

**Comment by ivanvza** [comment]
> 
> 
> Thank you for the proposal. Why the change to the BM file tho ?

Thank you for picking this up, I was using the BM Kill Command for troubleshooting some logic. I've amended it.

**Comment by Kutikuti** [comment]
Seemsgood, thank you

**Pull request merged**
