### PR TITLE
Druid Rotation

### PR DESCRIPTION
**Pull request by firesgc**
I have updated the old druid scripts to work with shadowlands. I do not want to maintain the rotation, but it might help someone as a starting point.

### CODE REVIEW

**Comment by Ankhy** [comment]
Getting this error:

Message: Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:314: attempt to get length of local 'Enemies' (a number value)
Time: Wed Dec  9 18:41:44 2020
Count: 72
Stack: Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua:314: attempt to get length of local 'Enemies' (a number value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HeroLib\Class\Unit\TimeToDie.lua"]:314: in function `FightRemains'
[string "@Interface\AddOns\HeroRotation_Druid\Balance.lua"]:235: in function `?'
[string "@Interface\AddOns\HeroRotation\Main.lua"]:445: in function <Interface\AddOns\HeroRotation\Main.lua:423>

**Comment by firesgc** [comment]
I only have a lvl20 druid and for this reason i can't really test it intensively :/
But I think I fixed it, and if you don't mind, you can download it from my branch and test it. (https://github.com/firesgc/hero-rotation). 
ps:
I have no idea how to easily update a pull requested from another fork, and imo GitHub/GitHub Desktop should be more user-friendly :-D

**Comment by Kutikuti** [comment]
Could you remove the changes to Blood and shadow in your PR and make separate PR for them if necessary ?

**Comment by Kutikuti** [comment]
There is way too many modifications in this pull request. I'm closing this one. mane a clean one if you want us to take a look

**Pull request closed without merging**
