### PR TITLE
Update Unholy.lua

### PR DESCRIPTION
**Pull request by Ankhy**

### CODE REVIEW

**Comment by Ankhy** [comment]
Probably a cleaner way to do this, but this works and you get the idea

**Comment by Ankhy** [comment]
Probably need to the same to aoe rotation as well

**Comment by chrislopez24** [comment]
Ill have a look at it tomorrow, have lot of irl work to do this weekend

**Comment by chrislopez24** [comment]
After investigation, the rotation being stuck is because of apoc.
The module is a direct translation of simc apl, and the simc robots always uses apoc
I have tried other ways to solve the problem without having to mess with the module a lot, but thinking in  the future development of the apl and the module I  decided that the best thing is to take the ability off  of "cds" and convert it into a normal skill, giving as an option to take it out of the main icon

**Pull request closed without merging**
