### PR TITLE
[Havoc] APL update and adjustments

### PR DESCRIPTION
**Pull request by talst**

### CODE REVIEW

**Comment by EvanMichaels** [comment]
Hi Talst, Meant to update the APL with the changes but forgot, thanks.

However, I see a few issues with this CL:
1) S.FelRush:Charges() == 2 being added doesn't always seem appropriate. That condition in the APL only kicks in when there are adds present in the fight. This would only apply on fights with add waves but there's no way of knowing that. I would be OK adding this as an option to the settings panel, but I don't think it should be default behavior.
2) The IsMetaExtendedByDemonic change doesn't make any sense to me logically. The only way you can tell if it's been extended already is to look at the cast time of Eye Beam vs. Meta. However this is somewhat moot because Blizzard ninja-changed Meta recently to be able to always extend.

**Comment by talst** [comment]
1. I assume you mean line 347, yeah I get what you are saying it just feels nicer to me.
I can revert this change but an option in the settings would be nice.
2. Isn't this is what extended meta is? Just a meta that is longer than 30 sec? it's the simplest way to define it (I usually prefer say what instead of how, more functional).
An earlier eye beam still extend the meta, if you follow the current suggested opener you will always pop eye beam before meta.

**Comment by EvanMichaels** [comment]
Heya, the purpose of the "extended meta" was to check that Demonic had not previously extended the duration of the active Metamorphpsis. Before a few weeks ago, you were only allowed to extend a single Metamorphosis buff once with Demonic, regardless of the number of Eye Beams cast. 

But you could reset this by doing Eye Beam -> Meta -> Eye Beam.

However, ExtendedByDemonic can now just return FALSE always, because Blizzard ninja-removed this mechanic in some hotfix recently.

**Comment by EvanMichaels** [comment]
Great, thanks a lot for the PR!

**Pull request merged**
